--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/berkeyaman/y
build-by-default: true
branches:
- main
projects: []minecraft mod How to Train Your Minecraft Dragon Mod minecraft mod How to Train Your Minecraft Dragon Mod
...
